vulnerabilities:
  - id: CVE-2026-25547
    statement: "@isaacs/brace-expansion has Uncontrolled Resource Consumption"
    purls:
      - "pkg:npm/%40isaacs/brace-expansion@5.0.0"
    expired_at: 2026-06-01
  - id: CVE-2021-3807
    statement: "nodejs-ansi-regex  Regular expression denial of service (ReDoS) matching ANSI escape codes"
    purls:
      - "pkg:npm/ansi-regex@3.0.0"
    expired_at: 2026-06-01
  - id: CVE-2021-3807
    statement: "nodejs-ansi-regex  Regular expression denial of service (ReDoS) matching ANSI escape codes"
    purls:
      - "pkg:npm/ansi-regex@5.0.0"
    expired_at: 2026-06-01
  - id: CVE-2025-64756
    statement: "glob  glob  Command Injection Vulnerability via Malicious Filenames"
    purls:
      - "pkg:npm/glob@10.4.5"
    expired_at: 2026-06-01
  - id: CVE-2025-64756
    statement: "glob  glob  Command Injection Vulnerability via Malicious Filenames"
    purls:
      - "pkg:npm/glob@11.0.3"
    expired_at: 2026-06-01
  - id: CVE-2022-25881
    statement: "http-cache-semantics  Regular Expression Denial of Service (ReDoS) vulnerability"
    purls:
      - "pkg:npm/http-cache-semantics@4.1.0"
    expired_at: 2026-06-01
  - id: CVE-2024-29415
    statement: "node-ip  Incomplete fix for CVE-2023-42282"
    purls:
      - "pkg:npm/ip@1.1.5"
    expired_at: 2026-06-01
  - id: CVE-2022-3517
    statement: "nodejs-minimatch  ReDoS via the braceExpand function"
    purls:
      - "pkg:npm/minimatch@3.0.4"
    expired_at: 2026-06-01
  - id: CVE-2026-0775
    statement: "npmcli  npm cli Incorrect Permission Assignment Local Privilege Escalation Vulnerability"
    purls:
      - "pkg:npm/npm@11.6.2"
    expired_at: 2026-06-01
  - id: CVE-2022-29244
    statement: "nodejs  npm pack ignores root-level .gitignore and .npmignore file exclusion directives when run in a workspace"
    purls:
      - "pkg:npm/npm@8.5.0"
    expired_at: 2026-06-01
  - id: CVE-2026-0775
    statement: "npmcli  npm cli Incorrect Permission Assignment Local Privilege Escalation Vulnerability"
    purls:
      - "pkg:npm/npm@8.5.0"
    expired_at: 2026-06-01
  - id: CVE-2022-25883
    statement: "nodejs-semver  Regular expression denial of service"
    purls:
      - "pkg:npm/semver@7.3.5"
    expired_at: 2026-06-01
  - id: CVE-2026-23745
    statement: "node-tar  tar  node-tar  Arbitrary file overwrite and symlink poisoning via unsanitized linkpaths in archives"
    purls:
      - "pkg:npm/tar@6.1.11"
    expired_at: 2026-06-01
  - id: CVE-2026-23950
    statement: "node-tar  tar  node-tar  Arbitrary file overwrite via Unicode path collision race condition"
    purls:
      - "pkg:npm/tar@6.1.11"
    expired_at: 2026-06-01
  - id: CVE-2026-24842
    statement: "node-tar  tar  node-tar  Arbitrary file creation via path traversal bypass in hardlink security check"
    purls:
      - "pkg:npm/tar@6.1.11"
    expired_at: 2026-06-01
  - id: CVE-2026-23745
    statement: "node-tar  tar  node-tar  Arbitrary file overwrite and symlink poisoning via unsanitized linkpaths in archives"
    purls:
      - "pkg:npm/tar@7.5.1"
    expired_at: 2026-06-01
  - id: CVE-2026-23950
    statement: "node-tar  tar  node-tar  Arbitrary file overwrite via Unicode path collision race condition"
    purls:
      - "pkg:npm/tar@7.5.1"
    expired_at: 2026-06-01
  - id: CVE-2026-24842
    statement: "node-tar  tar  node-tar  Arbitrary file creation via path traversal bypass in hardlink security check"
    purls:
      - "pkg:npm/tar@7.5.1"
    expired_at: 2026-06-01
  - id: CVE-2022-40897
    statement: "pypa-setuptools  Regular Expression Denial of Service (ReDoS) in package_index.py"
    purls:
      - "pkg:pypi/setuptools@56.0.0"
    expired_at: 2026-06-01
  - id: CVE-2024-6345
    statement: "pypa/setuptools  Remote code execution via download functions in the package_index module in pypa/setuptools"
    purls:
      - "pkg:pypi/setuptools@56.0.0"
    expired_at: 2026-06-01
  - id: CVE-2025-47273
    statement: "setuptools  Path Traversal Vulnerability in setuptools PackageIndex"
    purls:
      - "pkg:pypi/setuptools@56.0.0"
    expired_at: 2026-06-01
  - id: CVE-2022-40897
    statement: "pypa-setuptools  Regular Expression Denial of Service (ReDoS) in package_index.py"
    purls:
      - "pkg:pypi/setuptools@65.5.0"
    expired_at: 2026-06-01
  - id: CVE-2024-6345
    statement: "pypa/setuptools  Remote code execution via download functions in the package_index module in pypa/setuptools"
    purls:
      - "pkg:pypi/setuptools@65.5.0"
    expired_at: 2026-06-01
  - id: CVE-2025-47273
    statement: "setuptools  Path Traversal Vulnerability in setuptools PackageIndex"
    purls:
      - "pkg:pypi/setuptools@65.5.0"
    expired_at: 2026-06-01
  - id: CVE-2024-49761
    statement: "rexml  REXML ReDoS vulnerability"
    purls:
      - "pkg:gem/rexml@3.2.6"
    expired_at: 2026-06-01
  - id: CVE-2025-61726
    statement: "golang  net/url  Memory exhaustion in query parameter parsing in net/url"
    purls:
      - "pkg:golang/stdlib@v1.25.5"
    expired_at: 2026-06-01
  - id: CVE-2025-61728
    statement: "golang  archive/zip  Excessive CPU consumption when building archive index in archive/zip"
    purls:
      - "pkg:golang/stdlib@v1.25.5"
    expired_at: 2026-06-01
  - id: CVE-2025-47907
    statement: "database/sql  Postgres Scan Race Condition"
    purls:
      - "pkg:golang/stdlib@v1.24.4"
    expired_at: 2026-06-01
  - id: CVE-2025-58183
    statement: "golang  archive/tar  Unbounded allocation when parsing GNU sparse map"
    purls:
      - "pkg:golang/stdlib@v1.24.4"
    expired_at: 2026-06-01
  - id: CVE-2025-61726
    statement: "golang  net/url  Memory exhaustion in query parameter parsing in net/url"
    purls:
      - "pkg:golang/stdlib@v1.24.4"
    expired_at: 2026-06-01
  - id: CVE-2025-61728
    statement: "golang  archive/zip  Excessive CPU consumption when building archive index in archive/zip"
    purls:
      - "pkg:golang/stdlib@v1.24.4"
    expired_at: 2026-06-01
  - id: CVE-2025-61729
    statement: "crypto/x509  golang  Denial of Service due to excessive resource consumption via crafted certificate"
    purls:
      - "pkg:golang/stdlib@v1.24.4"
    expired_at: 2026-06-01
  - id: CVE-2025-22874
    statement: "crypto/x509  Usage of ExtKeyUsageAny disables policy validation in crypto/x509"
    purls:
      - "pkg:golang/stdlib@v1.24.3"
    expired_at: 2026-06-01
  - id: CVE-2025-47907
    statement: "database/sql  Postgres Scan Race Condition"
    purls:
      - "pkg:golang/stdlib@v1.24.3"
    expired_at: 2026-06-01
  - id: CVE-2025-58183
    statement: "golang  archive/tar  Unbounded allocation when parsing GNU sparse map"
    purls:
      - "pkg:golang/stdlib@v1.24.3"
    expired_at: 2026-06-01
  - id: CVE-2025-61726
    statement: "golang  net/url  Memory exhaustion in query parameter parsing in net/url"
    purls:
      - "pkg:golang/stdlib@v1.24.3"
    expired_at: 2026-06-01
  - id: CVE-2025-61728
    statement: "golang  archive/zip  Excessive CPU consumption when building archive index in archive/zip"
    purls:
      - "pkg:golang/stdlib@v1.24.3"
    expired_at: 2026-06-01
  - id: CVE-2025-61729
    statement: "crypto/x509  golang  Denial of Service due to excessive resource consumption via crafted certificate"
    purls:
      - "pkg:golang/stdlib@v1.24.3"
    expired_at: 2026-06-01
  - id: CVE-2025-66564
    statement: "github.com/sigstore/timestamp-authority  Sigstore Timestamp Authority  Denial of Service via excessive OID or Content-Type header parsing"
    purls:
      - "pkg:golang/github.com/sigstore/timestamp-authority@v1.2.2"
    expired_at: 2026-06-01
  - id: CVE-2025-47907
    statement: "database/sql  Postgres Scan Race Condition"
    purls:
      - "pkg:golang/stdlib@v1.23.4"
    expired_at: 2026-06-01
  - id: CVE-2025-58183
    statement: "golang  archive/tar  Unbounded allocation when parsing GNU sparse map"
    purls:
      - "pkg:golang/stdlib@v1.23.4"
    expired_at: 2026-06-01
  - id: CVE-2025-61726
    statement: "golang  net/url  Memory exhaustion in query parameter parsing in net/url"
    purls:
      - "pkg:golang/stdlib@v1.23.4"
    expired_at: 2026-06-01
  - id: CVE-2025-61728
    statement: "golang  archive/zip  Excessive CPU consumption when building archive index in archive/zip"
    purls:
      - "pkg:golang/stdlib@v1.23.4"
    expired_at: 2026-06-01
  - id: CVE-2025-61729
    statement: "crypto/x509  golang  Denial of Service due to excessive resource consumption via crafted certificate"
    purls:
      - "pkg:golang/stdlib@v1.23.4"
    expired_at: 2026-06-01
  - id: CVE-2023-24538
    statement: "golang  html/template  backticks not treated as string delimiters"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2023-24540
    statement: "golang  html/template  improper handling of JavaScript whitespace"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2024-24790
    statement: "golang  net/netip  Unexpected behavior from Is methods for IPv4-mapped IPv6 addresses"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2022-24675
    statement: "golang  encoding/pem  fix stack overflow in Decode"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2022-27664
    statement: "golang  net/http  handle server errors after sending GOAWAY"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2022-28131
    statement: "golang  encoding/xml  stack exhaustion in Decoder.Skip"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2022-28327
    statement: "golang  crypto/elliptic  panic caused by oversized scalar"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2022-2879
    statement: "golang  archive/tar  github.com/vbatts/tar-split  unbounded memory consumption when reading headers"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2022-2880
    statement: "golang  net/http/httputil  ReverseProxy should not forward unparseable query parameters"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2022-29804
    statement: "ELSA-2022-17957  ol8addon security update (IMPORTANT)"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2022-30580
    statement: "golang  os/exec  Code injection in Cmd.Start"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2022-30630
    statement: "golang  io/fs  stack exhaustion in Glob"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2022-30631
    statement: "golang  compress/gzip  stack exhaustion in Reader.Read"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2022-30632
    statement: "golang  path/filepath  stack exhaustion in Glob"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2022-30633
    statement: "golang  encoding/xml  stack exhaustion in Unmarshal"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2022-30634
    statement: "ELSA-2022-17957  ol8addon security update (IMPORTANT)"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2022-30635
    statement: "golang  encoding/gob  stack exhaustion in Decoder.Decode"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2022-32189
    statement: "golang  math/big  decoding big.Float and big.Rat types can panic if the encoded message is too short, potentially allowing a denial of service"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2022-41715
    statement: "golang  regexp/syntax  limit memory used by parsing regexps"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2022-41716
    statement: "Due to unsanitized NUL values, attackers may be able to maliciously se ..."
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2022-41720
    statement: "golang  os, net/http  avoid escapes from os.DirFS and http.Dir on Windows"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2022-41722
    statement: "golang  path/filepath  path-filepath filepath.Clean path traversal"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2022-41723
    statement: "golang.org/x/net/http2  avoid quadratic complexity in HPACK decoding"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2022-41724
    statement: "golang  crypto/tls  large handshake records may cause panics"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2022-41725
    statement: "golang  net/http, mime/multipart  denial of service from excessive resource consumption"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2023-24534
    statement: "golang  net/http, net/textproto  denial of service from excessive memory allocation"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2023-24536
    statement: "golang  net/http, net/textproto, mime/multipart  denial of service from excessive resource consumption"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2023-24537
    statement: "golang  go/parser  Infinite loop in parsing"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2023-24539
    statement: "golang  html/template  improper sanitization of CSS values"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2023-29400
    statement: "golang  html/template  improper handling of empty HTML attributes"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2023-29403
    statement: "golang  runtime  unexpected behavior of setuid/setgid binaries"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2023-39325
    statement: "golang  net/http, x/net/http2  rapid stream resets can cause excessive work (CVE-2023-44487)"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2023-45283
    statement: "The filepath package does not recognize paths with a prefix as sp ..."
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2023-45287
    statement: "golang  crypto/tls  Timing Side Channel attack in RSA based TLS key exchanges."
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2023-45288
    statement: "golang  net/http, x/net/http2  unlimited number of CONTINUATION frames causes DoS"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2024-34156
    statement: "encoding/gob  golang  Calling Decoder.Decode on a message which contains deeply nested structures can cause a panic due to stack exhaustion"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2025-47907
    statement: "database/sql  Postgres Scan Race Condition"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2025-58183
    statement: "golang  archive/tar  Unbounded allocation when parsing GNU sparse map"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2025-61726
    statement: "golang  net/url  Memory exhaustion in query parameter parsing in net/url"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2025-61728
    statement: "golang  archive/zip  Excessive CPU consumption when building archive index in archive/zip"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2025-61729
    statement: "crypto/x509  golang  Denial of Service due to excessive resource consumption via crafted certificate"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-06-01
  - id: CVE-2024-25621
    statement: "github.com/containerd/containerd  containerd local privilege escalation"
    purls:
      - "pkg:golang/github.com/containerd/containerd/v2@v2.1.4"
    expired_at: 2026-06-01
  - id: CVE-2025-61726
    statement: "golang  net/url  Memory exhaustion in query parameter parsing in net/url"
    purls:
      - "pkg:golang/stdlib@v1.24.9"
    expired_at: 2026-06-01
  - id: CVE-2025-61728
    statement: "golang  archive/zip  Excessive CPU consumption when building archive index in archive/zip"
    purls:
      - "pkg:golang/stdlib@v1.24.9"
    expired_at: 2026-06-01
  - id: CVE-2025-61729
    statement: "crypto/x509  golang  Denial of Service due to excessive resource consumption via crafted certificate"
    purls:
      - "pkg:golang/stdlib@v1.24.9"
    expired_at: 2026-06-01
  - id: CVE-2024-35870
    statement: "kernel: smb: client: fix UAF in smb2_reconnect_server()"
    purls:
      - "pkg:deb/ubuntu/linux-libc-dev@5.15.0-168.178?arch=amd64\u0026distro=ubuntu-22.04"
    expired_at: 2026-06-01
  - id: CVE-2024-53179
    statement: "kernel: smb: client: fix use-after-free of signing key"
    purls:
      - "pkg:deb/ubuntu/linux-libc-dev@5.15.0-168.178?arch=amd64\u0026distro=ubuntu-22.04"
    expired_at: 2026-06-01
  - id: CVE-2025-21780
    statement: "kernel: drm/amdgpu: avoid buffer overflow attach in smu_sys_set_pp_table()"
    purls:
      - "pkg:deb/ubuntu/linux-libc-dev@5.15.0-168.178?arch=amd64\u0026distro=ubuntu-22.04"
    expired_at: 2026-06-01
  - id: CVE-2025-37899
    statement: "kernel: ksmbd: fix use-after-free in session logoff"
    purls:
      - "pkg:deb/ubuntu/linux-libc-dev@5.15.0-168.178?arch=amd64\u0026distro=ubuntu-22.04"
    expired_at: 2026-06-01
  - id: CVE-2025-38118
    statement: "kernel: Linux kernel: Bluetooth MGMT use-after-free vulnerability allows privilege escalation"
    purls:
      - "pkg:deb/ubuntu/linux-libc-dev@5.15.0-168.178?arch=amd64\u0026distro=ubuntu-22.04"
    expired_at: 2026-06-01
  - id: CVE-2024-35870
    statement: "kernel: smb: client: fix UAF in smb2_reconnect_server()"
    purls:
      - "pkg:deb/ubuntu/linux-libc-dev@5.15.0-168.178?arch=arm64\u0026distro=ubuntu-22.04"
    expired_at: 2026-06-01
  - id: CVE-2024-53179
    statement: "kernel: smb: client: fix use-after-free of signing key"
    purls:
      - "pkg:deb/ubuntu/linux-libc-dev@5.15.0-168.178?arch=arm64\u0026distro=ubuntu-22.04"
    expired_at: 2026-06-01
  - id: CVE-2025-21780
    statement: "kernel: drm/amdgpu: avoid buffer overflow attach in smu_sys_set_pp_table() "
    purls:
      - "pkg:deb/ubuntu/linux-libc-dev@5.15.0-168.178?arch=arm64\u0026distro=ubuntu-22.04"
    expired_at: 2026-06-01
  - id: CVE-2025-37899
    statement: "kernel: ksmbd: fix use-after-free in session logoff"
    purls:
      - "pkg:deb/ubuntu/linux-libc-dev@5.15.0-168.178?arch=arm64\u0026distro=ubuntu-22.04"
    expired_at: 2026-06-01
  - id: CVE-2025-38118
    statement: "kernel: Linux kernel: Bluetooth MGMT use-after-free vulnerability allows privilege escalation"
    purls:
      - "pkg:deb/ubuntu/linux-libc-dev@5.15.0-168.178?arch=arm64\u0026distro=ubuntu-22.04"
    expired_at: 2026-06-01
