vulnerabilities:
  - id: CVE-2024-35870
    statement: "kernel: smb: client: fix UAF in smb2_reconnect_server()"
    purls:
      - "pkg:deb/ubuntu/linux-libc-dev@5.15.0-170.180?arch=amd64&distro=ubuntu-22.04"
    expired_at: 2026-08-12
  - id: CVE-2024-53179
    statement: "kernel: smb: client: fix use-after-free of signing key"
    purls:
      - "pkg:deb/ubuntu/linux-libc-dev@5.15.0-170.180?arch=amd64&distro=ubuntu-22.04"
    expired_at: 2026-08-12
  - id: CVE-2025-37849
    statement: "kernel: KVM: arm64: Tear down vGIC on failed vCPU creation"
    purls:
      - "pkg:deb/ubuntu/linux-libc-dev@5.15.0-170.180?arch=amd64&distro=ubuntu-22.04"
    expired_at: 2026-08-12
  - id: CVE-2025-37899
    statement: "kernel: ksmbd: fix use-after-free in session logoff"
    purls:
      - "pkg:deb/ubuntu/linux-libc-dev@5.15.0-170.180?arch=amd64&distro=ubuntu-22.04"
    expired_at: 2026-08-12
  - id: CVE-2025-38118
    statement: "kernel: Linux kernel: Bluetooth MGMT use-after-free vulnerability allows privilege escalation"
    purls:
      - "pkg:deb/ubuntu/linux-libc-dev@5.15.0-170.180?arch=amd64&distro=ubuntu-22.04"
    expired_at: 2026-08-12
  - id: CVE-2026-26007
    statement: "cryptography: cryptography Subgroup Attack Due to Missing Subgroup Validation for SECT Curves"
    purls:
      - "pkg:pypi/cryptography@46.0.3"
    expired_at: 2026-08-12
  - id: CVE-2024-49761
    statement: "rexml: REXML ReDoS vulnerability"
    purls:
      - "pkg:gem/rexml@3.2.6"
    expired_at: 2026-08-12
  - id: CVE-2025-68121
    statement: "During session resumption in crypto/tls, if the underlying Config has  ..."
    purls:
      - "pkg:golang/stdlib@v1.16.15"
      - "pkg:golang/stdlib@v1.23.4"
      - "pkg:golang/stdlib@v1.24.4"
      - "pkg:golang/stdlib@v1.24.9"
      - "pkg:golang/stdlib@v1.25.5"
    expired_at: 2026-08-12
  - id: CVE-2025-61726
    statement: "golang: net/url: Memory exhaustion in query parameter parsing in net/url"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
      - "pkg:golang/stdlib@v1.23.4"
      - "pkg:golang/stdlib@v1.24.4"
      - "pkg:golang/stdlib@v1.24.9"
      - "pkg:golang/stdlib@v1.25.5"
    expired_at: 2026-08-12
  - id: CVE-2025-61728
    statement: "golang: archive/zip: Excessive CPU consumption when building archive index in archive/zip"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
      - "pkg:golang/stdlib@v1.23.4"
      - "pkg:golang/stdlib@v1.24.4"
      - "pkg:golang/stdlib@v1.24.9"
      - "pkg:golang/stdlib@v1.25.5"
    expired_at: 2026-08-12
  - id: CVE-2025-61730
    statement: "During the TLS 1.3 handshake if multiple messages are sent in records  ..."
    purls:
      - "pkg:golang/stdlib@v1.16.15"
      - "pkg:golang/stdlib@v1.23.4"
      - "pkg:golang/stdlib@v1.24.4"
      - "pkg:golang/stdlib@v1.24.9"
      - "pkg:golang/stdlib@v1.25.5"
    expired_at: 2026-08-12
  - id: CVE-2025-47907
    statement: "database/sql: Postgres Scan Race Condition"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
      - "pkg:golang/stdlib@v1.23.4"
      - "pkg:golang/stdlib@v1.24.4"
    expired_at: 2026-08-12
  - id: CVE-2025-58183
    statement: "golang: archive/tar: Unbounded allocation when parsing GNU sparse map"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
      - "pkg:golang/stdlib@v1.23.4"
      - "pkg:golang/stdlib@v1.24.4"
    expired_at: 2026-08-12
  - id: CVE-2025-61729
    statement: "crypto/x509: golang: Denial of Service due to excessive resource consumption via crafted certificate"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
      - "pkg:golang/stdlib@v1.23.4"
      - "pkg:golang/stdlib@v1.24.4"
      - "pkg:golang/stdlib@v1.24.9"
    expired_at: 2026-08-12
  - id: CVE-2023-24538
    statement: "golang: html/template: backticks not treated as string delimiters"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-08-12
  - id: CVE-2023-24540
    statement: "golang: html/template: improper handling of JavaScript whitespace"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-08-12
  - id: CVE-2024-24790
    statement: "golang: net/netip: Unexpected behavior from Is methods for IPv4-mapped IPv6 addresses"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-08-12
  - id: CVE-2022-24675
    statement: "golang: encoding/pem: fix stack overflow in Decode"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-08-12
  - id: CVE-2022-27664
    statement: "golang: net/http: handle server errors after sending GOAWAY"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-08-12
  - id: CVE-2022-28131
    statement: "golang: encoding/xml: stack exhaustion in Decoder.Skip"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-08-12
  - id: CVE-2022-28327
    statement: "golang: crypto/elliptic: panic caused by oversized scalar"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-08-12
  - id: CVE-2022-2879
    statement: "golang: archive/tar: github.com/vbatts/tar-split: unbounded memory consumption when reading headers"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-08-12
  - id: CVE-2022-2880
    statement: "golang: net/http/httputil: ReverseProxy should not forward unparseable query parameters"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-08-12
  - id: CVE-2022-29804
    statement: "ELSA-2022-17957: ol8addon security update (IMPORTANT)"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-08-12
  - id: CVE-2022-30580
    statement: "golang: os/exec: Code injection in Cmd.Start"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-08-12
  - id: CVE-2022-30630
    statement: "golang: io/fs: stack exhaustion in Glob"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-08-12
  - id: CVE-2022-30631
    statement: "golang: compress/gzip: stack exhaustion in Reader.Read"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-08-12
  - id: CVE-2022-30632
    statement: "golang: path/filepath: stack exhaustion in Glob"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-08-12
  - id: CVE-2022-30633
    statement: "golang: encoding/xml: stack exhaustion in Unmarshal"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-08-12
  - id: CVE-2022-30634
    statement: "ELSA-2022-17957: ol8addon security update (IMPORTANT)"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-08-12
  - id: CVE-2022-30635
    statement: "golang: encoding/gob: stack exhaustion in Decoder.Decode"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-08-12
  - id: CVE-2022-32189
    statement: "golang: math/big: decoding big.Float and big.Rat types can panic if the encoded message is too short, potentially allowing a denial of service"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-08-12
  - id: CVE-2022-41715
    statement: "golang: regexp/syntax: limit memory used by parsing regexps"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-08-12
  - id: CVE-2022-41716
    statement: "Due to unsanitized NUL values, attackers may be able to maliciously se ..."
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-08-12
  - id: CVE-2022-41720
    statement: "golang: os, net/http: avoid escapes from os.DirFS and http.Dir on Windows"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-08-12
  - id: CVE-2022-41722
    statement: "golang: path/filepath: path-filepath filepath.Clean path traversal"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-08-12
  - id: CVE-2022-41723
    statement: "golang.org/x/net/http2: avoid quadratic complexity in HPACK decoding"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-08-12
  - id: CVE-2022-41724
    statement: "golang: crypto/tls: large handshake records may cause panics"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-08-12
  - id: CVE-2022-41725
    statement: "golang: net/http, mime/multipart: denial of service from excessive resource consumption"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-08-12
  - id: CVE-2023-24534
    statement: "golang: net/http, net/textproto: denial of service from excessive memory allocation"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-08-12
  - id: CVE-2023-24536
    statement: "golang: net/http, net/textproto, mime/multipart: denial of service from excessive resource consumption"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-08-12
  - id: CVE-2023-24537
    statement: "golang: go/parser: Infinite loop in parsing"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-08-12
  - id: CVE-2023-24539
    statement: "golang: html/template: improper sanitization of CSS values"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-08-12
  - id: CVE-2023-29400
    statement: "golang: html/template: improper handling of empty HTML attributes"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-08-12
  - id: CVE-2023-29403
    statement: "golang: runtime: unexpected behavior of setuid/setgid binaries"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-08-12
  - id: CVE-2023-39325
    statement: "golang: net/http, x/net/http2: rapid stream resets can cause excessive work (CVE-2023-44487)"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-08-12
  - id: CVE-2023-45283
    statement: "The filepath package does not recognize paths with a \\??\\ prefix as sp ..."
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-08-12
  - id: CVE-2023-45287
    statement: "golang: crypto/tls: Timing Side Channel attack in RSA based TLS key exchanges."
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-08-12
  - id: CVE-2023-45288
    statement: "golang: net/http, x/net/http2: unlimited number of CONTINUATION frames causes DoS"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-08-12
  - id: CVE-2024-34156
    statement: "encoding/gob: golang: Calling Decoder.Decode on a message which contains deeply nested structures can cause a panic due to stack exhaustion"
    purls:
      - "pkg:golang/stdlib@v1.16.15"
    expired_at: 2026-08-12
  - id: CVE-2024-25621
    statement: "github.com/containerd/containerd: containerd local privilege escalation"
    purls:
      - "pkg:golang/github.com/containerd/containerd/v2@v2.1.4"
    expired_at: 2026-08-12
  - id: CVE-2024-35870
    statement: "kernel: smb: client: fix UAF in smb2_reconnect_server()"
    purls:
      - "pkg:deb/ubuntu/linux-libc-dev@5.15.0-170.180?arch=arm64&distro=ubuntu-22.04"
    expired_at: 2026-08-12
  - id: CVE-2024-53179
    statement: "kernel: smb: client: fix use-after-free of signing key"
    purls:
      - "pkg:deb/ubuntu/linux-libc-dev@5.15.0-170.180?arch=arm64&distro=ubuntu-22.04"
    expired_at: 2026-08-12
  - id: CVE-2025-37849
    statement: "kernel: KVM: arm64: Tear down vGIC on failed vCPU creation"
    purls:
      - "pkg:deb/ubuntu/linux-libc-dev@5.15.0-170.180?arch=arm64&distro=ubuntu-22.04"
    expired_at: 2026-08-12
  - id: CVE-2025-37899
    statement: "kernel: ksmbd: fix use-after-free in session logoff"
    purls:
      - "pkg:deb/ubuntu/linux-libc-dev@5.15.0-170.180?arch=arm64&distro=ubuntu-22.04"
    expired_at: 2026-08-12
  - id: CVE-2025-38118
    statement: "kernel: Linux kernel: Bluetooth MGMT use-after-free vulnerability allows privilege escalation"
    purls:
      - "pkg:deb/ubuntu/linux-libc-dev@5.15.0-170.180?arch=arm64&distro=ubuntu-22.04"
    expired_at: 2026-08-12
