vulnerabilities:
  - id: CVE-2026-23949
    statement: "jaraco.context: jaraco.context: Path traversal via malicious tar archives"
    purls:
      - "pkg:pypi/jaraco.context@5.3.0"
    expired_at: 2026-08-12
  - id: CVE-2026-24049
    statement: "wheel: wheel: Privilege Escalation or Arbitrary Code Execution via malicious wheel file unpacking"
    purls:
      - "pkg:pypi/wheel@0.45.1"
    expired_at: 2026-08-12
